name: CI

on:
  pull_request:
  push:
    branches:
      - latest
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true
    - name: Build
      run: |
        npm ci
        npm run --workspaces build
    - name: Type check
      run: |
        npm run --workspaces --if-present ensure-no-project-compile-errors
    - name: Test
      run: |
        npm run --workspaces --if-present test:ci
        npm run --workspaces --if-present test:ts-versions
    - name: Code Verification
      run: |
        npm run --workspaces --if-present code-verification

  jsr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true
    - run: npm ci
    - name: Build
      run: npm run build:deno
    - name: Test
      run: cd deno && deno test --allow-read
    - name: Publish
      run: cd deno && deno publish --dry-run
