name: Publish
on:
  push:
    branches:
      - latest

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true
    - run: npm ci
    - name: Build
      run: npm run build:deno
    - name: Publish
      run: cd deno && deno publish
